# 🔗 链接:
# 源文件: https://github.com/obytes/react-native-template-obytes/blob/master/.github/actions/setup-node-pnpm-install/action.yml
# 组合操作文档: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

# ✍️ 描述:
# 这是一个组合操作，这意味着它可以在其他操作中使用。
# 它几乎在所有工作流中都使用，用于设置环境和安装依赖项。
# 在这里更新包管理器或 Node 版本将在所有工作流中反映出来。

# 👀 示例用法:
#       - name : 📦 Setup Node + PNPM + install deps
#         uses: ./.github/actions/setup-node-pnpm-install

name: 'Setup  Node + PNPM + Install Dependencies'
description: 'Setup  Node + PNPM + Install Dependencies'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: 📦 Install Project Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
