#!/bin/bash
# 這個簡單的腳本將獲取 Android 平台的最新構建 URL
./android/gradlew assembleRelease -p ./android # 構建 release 版 APK
find ./android -type f -name "app-release.apk" # 查找 apk 文件
adb install "<path_to_apk_file>" # 安裝 apk 文件
