# 🔗 連結：
# 來源檔案：https://github.com/obytes/react-native-template-obytes/blob/master/.github/workflows/compress-images.yml

# ✍️ 說明：
# 這個 workflow 用來壓縮 repo 內的圖片。
# 這個 workflow 會在推送到 "master" 或 "main" 分支時觸發，且只有新增或更新圖片時才會執行。
# 若符合條件，會壓縮那些圖片，並用壓縮後的圖片建立 pull request。

# 🚨 必要的 GITHUB SECRETS：無

name: Compress images
on:
  push:
    branches:
      - master
      - main
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
  workflow_dispatch:

jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          ignorePaths: 'node_modules/**,ios/**,android/**'

      - name: Create Pull Request
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v3
        with:
          title: Auto Compress Images
          branch-suffix: timestamp
          commit-message: Compress Images
          body: ${{ steps.calibre.outputs.markdown }}
