# 🔗 連結：
# 來源檔案：https://github.com/obytes/react-native-template-obytes/blob/master/.github/workflows/e2e-android.yml
# 端對端測試：https://starter.obytes.com/testing/end-to-end-testing/

# ✍️ 說明：
# 這個 workflow 會使用 Maestro Cloud 在 Android 上執行端對端測試。
# 第一步會使用 Gradle build 產生測試 APK，接著觸發 Maestro Cloud 對產生的 APK 執行測試。
# 這個 workflow 會在帶有 "android-test-maestro-cloud" 標籤的 pull request（PR）上觸發，也可以從 Actions 分頁手動觸發。

# 🚨 必要的 GITHUB SECRETS：
# MAESTRO_CLOUD_API_KEY：Maestro Cloud 的 API key。可從 https://cloud.mobile.dev/ci-integration/github-actions#add-your-api-key-secret 取得

name: E2E Tests Android (Maestro Cloud)

on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]

jobs:
  generate-and-test-apk:
    if: github.event_name != 'pull_request' || ( github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'android-test-maestro-cloud'))
    name: Generate and Test Test APK (Maestro Cloud)
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: 📦 Set Up JDK + Generate Test APK
        uses: ./.github/actions/setup-jdk-generate-apk
        with:
          APP_ENV: staging

      - name: Upload Test APK
        uses: actions/upload-artifact@v3
        with:
          name: test-apk
          path: ./android/app/build/outputs/apk/release/app-release.apk

      - name: 📱 Run E2E Tests with Maestro Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v1.4.1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: ./android/app/build/outputs/apk/release/app-release.apk
          env: |
            APP_ID=com.obytes.staging
