# 🔗 連結：
# 來源檔案：https://github.com/obytes/react-native-template-obytes/blob/master/.github/workflows/lint-ts.yml

# ✍️ 說明：
# 這個 action 用來執行 eslint 檢查。
# 會在 pull request 與推送到 main/master 分支時執行。
# 依據事件類型：
#   - 如果是 pull request，會執行 eslint，接著把檢查結果加入 PR，並在程式碼上標註錯誤與警告。
#   - 如果是推送到 main/master，會執行 type-check；若有任何錯誤就會失敗。

# 🚨 必要的 GITHUB SECRETS：無

name: Lint TS (eslint, prettier)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Lint TS (eslint, prettier)
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: 🏃‍♂️ Run ESLint PR
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: '. --ext .js,.jsx,.ts,.tsx'

      - name: 🏃‍♂️ Run ESLint PR
        if: github.event_name != 'pull_request'
        run: pnpm run lint
