# 🔗 連結：
# 來源檔案：https://github.com/obytes/react-native-template-obytes/blob/master/.github/workflows/test.yml

# ✍️ 說明：
# 這個 action 用來執行單元測試。
# 會在 pull request 與推送到 main/master 分支時執行。
# 依據事件類型：
#   - 如果是 pull request，會執行測試並留言提供 coverage 詳細資訊。
#   - 如果是推送到 main/master，會執行測試並將檢查結果加入 commit。

# 🚨 必要的 GITHUB SECRETS：無

name: Tests (jest)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Tests (jest)
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: 🏃‍♂️ Run Tests
        run: pnpm run test:ci

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        if: (success() || failure()) && github.event_name == 'pull_request'
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
          summary-title: 💯 Test Coverage
          badge-title: Coverage
          create-new-comment: false
          junitxml-title: 😎 Tests Results
          junitxml-path: ./coverage/jest-junit.xml
          coverage-title: 👀 Tests Details
          coverage-path: ./coverage/coverage.txt
          report-only-changed-files: true
