# 🔗 連結：
# 來源檔案：https://github.com/obytes/react-native-template-obytes/blob/master/.github/workflows/type-check.yml

# ✍️ 說明：
# 這個 action 用來對專案執行 type-check。
# 會在 pull request 與推送到 main/master 分支時執行。
# 依據事件類型：
#   - 如果是 pull request，會執行 type-check，接著把檢查結果加入 PR，並使用 reviewdog 在程式碼上標註錯誤。
#   - 如果是推送到 main/master，會執行 type-check；若有任何錯誤就會失敗。

# 🚨 必要的 GITHUB SECRETS：無

name: Type Check (tsc)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pull-requests: write

jobs:
  type-check:
    name: Type Check (tsc)
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: 📦 Install Reviewdog
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-setup@v1

      - name: 🏃‍♂️ Run TypeScript PR # Reviewdog tsc 錯誤格式：%f:%l:%c - error TS%n: %m
        # 只有 pull request 才需要加入 reviewdog 步驟
        if: github.event_name == 'pull_request'
        run: |
          pnpm type-check | reviewdog -name="tsc" -efm="%f(%l,%c): error TS%n: %m" -reporter="github-pr-review" -filter-mode="nofilter" -fail-on-error -tee
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name:
          🏃‍♂️ Run TypeScript Commit
          # 如果不是 Pull Request，只需要執行 type-check
        if: github.event_name != 'pull_request'
        run: pnpm type-check
